### PR TITLE
Refactored spanText

### PR DESCRIPTION
**Pull request by ivan-anic**
I thought that sending TextView as a parameter here is not the cleanest idea, in addition to sometimes wanting that spanned string as a variable.

With:
`val pero = TextView(this)
`
now you can write:
`pero.text = TextViewUtil.spanText(content, false) { launchUrl(it) }
`
(and also `val pero2 = TextViewUtil.spanText(content, false) { launchUrl(it, R.color.black) }`)

instead of old:
`TextViewUtil.spanText(pero, content, false)
`
or even

```
TextViewUtil.spanText(pero, "", false, object : TextViewUtil.OnUrlClickListener{
    override fun onUrlClicked(url: String) {
        launchUrl(url, R.color.black)
    }
})

```
Another benefit from this is that the context is not neccessary, (because it was required only to set the text which we don’t want, and launching customtabs, which is short enough on its own, especially because it’s an extension fun) so this can get called from anywhere just for the purpose of spanning text (what it’s name says it does :) ) 

Another thing, is this neccessary?
`var hrefSpannable = setCustomUrlSpans(SpannableString(htmlContent.spanHtml()), onUrlClick)
`
I remember that it maybe was, but perhaps we could lose setCustomUrlSpans()

`var hrefSpannable = SpannableString(htmlContent.spanHtml())
`

### CODE REVIEW

**Comment by tsmrecki** [comment]
Okay, seems fine, but maybe add a new method which prepares the TextView with link movement method and defaults the link clicks to launching the URL.
In many cases this is enough without any further customizations, so it's useful.

As for the double setCustomUrlSpans, yes, it's necessary. I've tried solutions without it, but couldn't make it work.
The first time it finds <a hrefs> and makes URLSpans for them.
After their behaviour is edited, then the Linkify.ALL is called and the plain text URLs (www.google.hr) are recognized and also spanned. It wouldn't work when calling Linkify.ALL before the first call of setCustomUrlSpans.

**Comment by ivan-anic** [comment]
> Okay, seems fine, but maybe add a new method which prepares the TextView with link movement method and defaults the link clicks to launching the URL.
> In many cases this is enough without any further customizations, so it's useful.
> 
> As for the double setCustomUrlSpans, yes, it's necessary. I've tried solutions without it, but couldn't make it work.
> The first time it finds and makes URLSpans for them.
> After their behaviour is edited, then the Linkify.ALL is called and the plain text URLs ([www.google.hr](http://www.google.hr)) are recognized and also spanned. It wouldn't work when calling Linkify.ALL before the first call of setCustomUrlSpans.

Thought about that for a while... setting the default is now as easy as { launchUrl(it) }, but only because it is an extension function over Context. Otherwise, a context would have to be passed in `TextViewUtil.spanText()` **just** for having the default custom tabs behavior.

And regarding the linkMovement, kinda the same thing, it's a fight between too defined, and not abstract enough. I agree that you can seldom forget setting the `linkMovementMethod`, but then I asked myself; "would it be cool to make a function which will combine a LinearLayoutManager, a ViewPager, and a RecyclerView?", and the answer was a clear no, because it's just a couple of simple lines of code.

About the spans, just wanted to check, I know that we've been through this for a long time 🗡 

- On a third thought, I'm thinking we could add the method... It would be useful, but it was ugly, java-like, and not so intuitive like it was before: `TextViewUtil.spanText(textview ... )`. Maybe an extension over TextView will be okay here.

**Comment by tsmrecki** [comment]
I'm OK with TextView extension function, you can add it.

**Comment by tsmrecki** [comment]
Added the mentioned extension function, will merge now.

**Review by tsmrecki — APPROVED** [review]

**Pull request merged**
